### ISSUE TITLE
Lock released twice in bot.py

### ISSUE THREAD

**Issue by luk3yx** [impredicative/irc-rss-feed-bot#38]
The lock is released here but not acquired again:

https://github.com/impredicative/irc-rss-feed-bot/blob/e23911e5202c049a2c29175ca5e08b7e538e478d/ircrssfeedbot/bot.py#L102-L110

**Comment by impredicative** [comment]
I will review the lock and release code carefully, although it has worked without any exception for months across hundreds of feeds, so I do think it is correct.

**Comment by impredicative** [comment]
The lock is acquired in the beginning lines of the `while` loop, and the only way out of the loop is via the `break` statement with the lock acquired.

**Comment by luk3yx** [comment]
Oh, I didn't see the indentation, sorry.
