### ISSUE TITLE
error ssl

### ISSUE THREAD

**Issue by bibidinu** [impredicative/irc-rss-feed-bot#46]
Hi guys i have 2 errors on bot someone can help me?

ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1108)

ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1108)

**Comment by impredicative** [comment]
Provide your Docker Compose and bot config.

**Comment by bibidinu** [comment]
docker-compose
version: '3.7'
services:
  irc-rss-feed-bot:
    container_name: irc-rss-feed-bot
    image: ascensive/irc-rss-feed-bot:latest
    restart: always
    logging:
      options:
        max-size: 2m
        max-file: "5"
    volumes:
      - ./irc-rss-feed-bot:/config
    env_file:
      - ./irc-rss-feed-bot/secrets.env

bot config 

host: irc.sweetsin.ltd
ssl_port: 9000
nick: SweetFeed

**Comment by impredicative** [comment]
Please format the YAML correctly in your reply, otherwise I cannot evaluate it. Refer to this [doc](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting). Instead of the `ruby` prefix, use the `yaml` prefix.

**Comment by bibidinu** [comment]
docker-compose.yml ->      https://pastebin.com/Mwb3nLx8
config.yaml ->                     https://pastebin.com/vjNA0QMJ


need more files ?

**Comment by impredicative** [comment]
You should not use `latest`. Use an explicit version instead, e.g. `0.9.9`. Without this you will have a very bad time if and when any breaking changes are made in a future version.

Is this connecting to your private IRC server? Is its SSL certificate valid? It's self-signed as confirmed by this [checker](https://www.sslshopper.com/ssl-checker.html#hostname=irc.sweetsin.ltd:9000) and that's the problem. If it's for your private server, why not get a proper cert from https://letsencrypt.org/ or elsewhere?

Or do you want me to give you an option to disable SSL?

**Comment by impredicative** [comment]
Try using version `0.9.10` which now allows more https certificates to be valid. I don't guarantee that this fixes your issue, however. I have lowered the SECLEVEL from 2 to 1. I'm not inclined to lower it to 0, however.

**Comment by bibidinu** [comment]
Ok thanks for your answer, last question, if i want disable ssl port irc it is possible?

**Comment by bibidinu** [comment]
last things bot is connect i have this error and bot dont talk 
is normal? 


AttributeError: 'types.SimpleNamespace' object has no attribute 'nick_casefold'

**Comment by impredicative** [comment]
Please show your minimal service config YAML and also a simplified instance config with just one feed.

**Comment by impredicative** [comment]
You failed to even confirm if the altered SECLEVEL fixed the server connection for you. Now you want help for an error but you don't want to share your fixed config.
