### ISSUE TITLE
Option to change the order?

### ISSUE THREAD

**Issue by mxmilkiib** [impredicative/irc-rss-feed-bot#71]
If two new items are added to an input feed, then it gets pulled and those items are messaged through, (it appears) the bot outputs them in the order those items are located in the feed, i.e., the first/latest entry at the top is output first, and an entry dated a few days ago (though only added to the input feed now) is output second.

I think it would make more sense if the items items were recounted to the channel in the reverse order, so the newest/latest entry would come out last. Does that make sense?

**Comment by impredicative** [comment]
> I think it would make more sense if the items items were recounted to the channel in the reverse order, so the newest/latest entry would come out last. 

It depends. If there are 5 new entries, then yes, maybe. If there are 25 or more new entries, then maybe I care about the newer ones more than I care about the older ones.

Anyway, this has never been an issue for me in practice. Is it really an issue for you to have a per-feed option to reverse the order?

**Comment by mxmilkiib** [comment]
If one cares about starting with newer messages in IRC, would one generally not read them from the bottom up? Indeed there are cases where reading a block of new links as a paragraph, from top to bottom, makes more sense. I think both cases are equally valid, but in my specific scenario, if I could have only one, it would be outputting the feed in reverse.

It is starting to be an issue;
![image](https://user-images.githubusercontent.com/108225/99152417-89e0e080-2699-11eb-8254-e3320def70df.png)

Aside from the case of adding a new feed to the aggregated feed, another factor is that I need to slow down on polling GH so the likelihood of two versions in a day, which will cause the same problem, will rise.

**Comment by impredicative** [comment]
I guess I'll add a non-default feed-specific option `order: reverse`. Standby.

**Comment by impredicative** [comment]
Released in `0.9.39`. I haven't tested the release, but it should be fine.
