### ISSUE TITLE
'types.SimpleNamespace' object has no attribute 'identity'

### ISSUE THREAD

**Issue by mxmilkiib** [impredicative/irc-rss-feed-bot#84]
I've just moved over to Libera.Chat, and, possibly unrelated (I don't think I updated Drupal that day), I', now seeing many; Error processing feed libreav of #libreav: 'types.SimpleNamespace' object has no attribute 'identity'

https://libreav.org/updates/feed

**Comment by impredicative** [comment]
1. Ensure the latest release of the bot is being used. Specify which version of the bot is in use.
2. Ensure the nick and password of the bot are registered, and that email verification is complete. Ensure this looks correct in the bot's configuration. Let me know.

**Comment by impredicative** [comment]
Someone I know (not me) is using the bot without any issues in say #securitynews on Libera, so overall it does work.

**Comment by mxmilkiib** [comment]
Bingo, it was registration, sorry for the noise!
